/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.streams.gironil;

import com.streams.SwingUtils;
import java.awt.Dialog;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Shehata.Ibrahim
 */
public abstract class SetupForm extends Dialog {

    JFileChooser jfcFileSelector = new JFileChooser();
    
    /**
     * Creates new form SetupForm
     */
    boolean exitOnClose=false;

    public SetupForm(Frame owner, boolean modal,boolean exitOnClose) {
        this(owner, modal);
        this.exitOnClose=exitOnClose;
    }
    
    public SetupForm(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        setSize(430, 180);
        SwingUtils.centerScreen(this);
        Properties conf = Configs.loadConfigurations(Configs.CONFIG_FILE_NAME);
        if (conf != null) {
            txtInput.setText(conf.getProperty(Configs.INPUT_FOLDER_KEY));
            txtProcessed.setText(conf.getProperty(Configs.PROCESSED_FOLDER_KEY));
            txtOutput.setText(conf.getProperty(Configs.OUTPUT_FOLDER_KEY));
        }
        jfcFileSelector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProccessed = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtProcessed = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        btnOutput = new javax.swing.JButton();
        btnBrowseInput = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();

        setResizable(false);
        setTitle("Paths Setup");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnProccessed.setText("Browse Processed Folder");
        btnProccessed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProccessedActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtProcessed.setEditable(false);
        txtProcessed.setMaximumSize(new java.awt.Dimension(213, 21));
        txtProcessed.setMinimumSize(new java.awt.Dimension(6, 21));
        txtProcessed.setPreferredSize(new java.awt.Dimension(213, 21));

        txtOutput.setEditable(false);
        txtOutput.setMaximumSize(new java.awt.Dimension(213, 21));
        txtOutput.setPreferredSize(new java.awt.Dimension(213, 21));

        btnOutput.setText("Browse Output Folder");
        btnOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputActionPerformed(evt);
            }
        });

        btnBrowseInput.setText("Browse Input Folder");
        btnBrowseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseInputActionPerformed(evt);
            }
        });

        txtInput.setEditable(false);
        txtInput.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(262, 262, 262)
                        .addComponent(btnSave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProcessed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProccessed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBrowseInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowseInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcessed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProccessed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        onDispose();
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(exitOnClose)
        {
            if(txtInput.getText().isEmpty() ||txtProcessed.getText().isEmpty()||txtOutput.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(btnSave, "This is first time setup so please:\nprovide the Input,Processed and Output Folders paths", "First Time Setup", WIDTH);
                return;
            }
        }
        try {
            Configs.saveConfigurations(txtInput.getText(), txtProcessed.getText(),txtOutput.getText());
            onSave();
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(btnSave, "Configuration saving error:\n" + ex.getMessage(), "Save Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private boolean isSave = false;
    private void btnProccessedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProccessedActionPerformed
        showFileSelector(txtProcessed);
    }//GEN-LAST:event_btnProccessedActionPerformed
    private void showFileSelector(JTextField txtComp) {
        if (!txtComp.getText().isEmpty()) {
            jfcFileSelector.setCurrentDirectory(new File(txtComp.getText()));
        }
        if (jfcFileSelector.showOpenDialog(txtComp) == JFileChooser.APPROVE_OPTION) {
            txtComp.setText(jfcFileSelector.getSelectedFile().getAbsolutePath());
        }
    }
    public abstract void onSave();
    private void btnOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputActionPerformed
        showFileSelector(txtOutput);
    }//GEN-LAST:event_btnOutputActionPerformed

    private void btnBrowseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseInputActionPerformed
        showFileSelector(txtInput);
    }//GEN-LAST:event_btnBrowseInputActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        onDispose();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseInput;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOutput;
    private javax.swing.JButton btnProccessed;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtProcessed;
    // End of variables declaration//GEN-END:variables

    public abstract void onDispose();
}
