
GO
CREATE TABLE [dbo].[TRANSACTIONS](
	[TRANSACTION_ID] [varchar](35) NOT NULL,
	[COMPANY_CODE] [varchar](10) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[ACCOUNT_NUMBER] [varchar](15) NOT NULL,
	[CUSTOMER_NAME] [varchar](50) NOT NULL,
	[CUSTOMER_REFERENCE] [varchar](20) NOT NULL,
	[AMOUNT] [real] NOT NULL,
	[BIC_CODE] [varchar](15) NOT NULL,
	[BRANCH_CODE] [varchar](15) NULL,
	[BATCH_ID] [varchar](35) NOT NULL,
	[TRANSACTION_SERIAL] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRANSACTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[FILES_BATCHES]    Script Date: 06/28/2015 13:45:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FILES_BATCHES](
	[FILE_NAME] [varchar](150) NOT NULL,
	[BATCH_ID] [varchar](35) NOT NULL,
	[INSERTION_TIME] [datetime] NOT NULL,
 CONSTRAINT [PK_FILES_BATCHES] PRIMARY KEY CLUSTERED 
(
	[BATCH_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[COMPANY_INFO]    Script Date: 06/28/2015 13:45:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMPANY_INFO](
	[CODE] [varchar](10) NOT NULL,
	[NAME] [varchar](35) NOT NULL,
	[TEMP_COLUMN] [varchar](35) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCHES]    Script Date: 06/28/2015 13:45:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCHES](
	[BATCH_ID] [varchar](35) NOT NULL,
	[COMPANY_CODE] [varchar](10) NOT NULL,
	[COMPANY_NAME] [varchar](35) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[NUMBER_OF_TRANSACTIONS] [int] NOT NULL,
	[TOTAL_AMOUNT] [real] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BATCH_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
